Vagrant.configure("2") do |config|
config.vm.provision "shell", inline: "echo hello"

config.vm.define "VM1" do |vm1|
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.hostname = "VM1"
    vm1.vm.network "private_network", ip: "192.168.56.31"
     
     config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

   vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y mysql-server mysql-client

      sudo apt-get -y install prometheus prometheus-node-exporter prometheus-pushgateway

     wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.0/mysqld_exporter-0.15.0.linux-amd64.tar.gz
     tar -xvf mysqld_exporter-0.15.0.linux-amd64.tar.gz
     sudo mv mysqld_exporter-0.15.0.linux-amd64/mysqld_exporter /usr/local/bin/
     sudo chmod +x /usr/local/bin/mysqld_exporter

     sudo service mysql start
     sudo mysql -u root -e "CREATE USER 'mysql_exporter'@'localhost' IDENTIFIED BY 'exporter';"
     sudo service mysql restart

     sudo bash -c 'echo -e "[client]" > /etc/.mysql_exporter.cnf
     echo "user=mysqld_exporter" >> /etc/.mysql_exporter.cnf
     echo "password=exporter" >> /etc/.mysql_exporter.cnf'
     sudo chown root:prometheus /etc/.mysql_exporter.cnf
   
     sudo bash -c 'echo -e "[Unit]\n\
     Description=Prometheus MySQL Exporter\n\
     After=network.target\n\n\
     [Service]\n\
     User=prometheus\n\
     Group=prometheus\n\
     Environment=\"DATA_SOURCE_NAME=mysql_exporter:exporter@(192.168.56.31:3306)"\n\
     Type=simple\n\
     ExecStart=/usr/local/bin/mysqld_exporter --config.my-cnf /etc/.mysql_exporter.cnf\n\
     Restart=always\n\n\
     [Install]\n\
     WantedBy=multi-user.target" > /etc/systemd/system/mysqld_exporter.service'

     sudo systemctl daemon-reload
     sudo systemctl enable mysqld_exporter
     sudo systemctl start mysqld_exporter

     sudo touch shop-database.sql
     sudo mysql -e "CREATE DATABASE shop;"
     sudo shop-database.sql > mysql shop
    SHELL
end


   config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/ubuntu-22.04"
    vm2.vm.hostname = "VM2"
    vm2.vm.network "private_network", ip: "192.168.56.32"
     
     config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkkS+/9jCE7HpwdJhhCb8sEWlmHMN6RhsREi8z2pbaojYp1KJc2p5bgd4+OEVhqVEHIKCbd8qLgVdtcEsKzYak+TV6MEK1K9aOek1AUPakt/7+iBIcWVSB01lka6Fs0pU9ifwc792u7k2TROJORHcmQiFHKXQxq3LpKQFt5Mn5RV/U/0sHv2RUfNHShCr+sUgxnfgoNRgx20p0xPnt462ryQu5GGS40fLlKCugg5aZrev4tdP6xnP1/I/EVk3JR25L+kTBetbRZNeV3WQxfMJlKbu7n3iw0rTKB/FMTQkLdXL3bAMF14RuA7/RzOmE3YTZrMANDuVwxbjgudR8bwmK/r2Fez9FAf5abauaVI/QUCURc2rRcy5CI20WcxIdy3I+mytKTKNolzRYH3+G15sczTKlfQSyb/mH+2O/kricCqq8xJZ9Xf1Kg+xubGkk7quivk2aIXYaFZaHO+VMVX4Dpy67Wm+UdAsRtCnHuPBX4NLpxbQANuE3QblxtiCYh/EXLyAa7XuWJryj9/EMh/o6lWtvbbchmlyAn/BN/P9u552UfQS3+xyActiMhQlg3rCb0tYuUoYb6n9z7YbEF0T3DaoMtYPAvDcUpu7zNhuac27D01r9KyoconZyg1U7HzZC8iN4Aukc6qSV2Fof1oRA+fKiWxbfeuCfs8aMeABPYw== your_email@example.com'
  sudo chmod 600 /home/vagrant/.ssh/authorized_keys
  sudo chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys

  sudo apt-get install -y software-properties-common
  sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"

  wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 963FA27710458545
 
  sudo apt-get update
  sudo apt-get install -y grafana prometheus prometheus-node-exporter prometheus-pushgateway

  wget https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
  tar xvzf alertmanager-0.26.0.linux-amd64.tar.gz
  sudo cp alertmanager-0.26.0.linux-amd64/alertmanager /usr/local/bin/

  cat <<EOF | sudo tee /etc/systemd/systems/alertmanager.service
 [Unit]
Description= AlertManager server service
Wants=network-online.target
After=network.target

[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/local/bin/alertmanager \
    --config.file /etc/alertmanager/alertmanager.yml \
    --storage.path /var/lib/alertmanager/data
Restart=always
[Install]
WantedBy=multi-user.target
EOF

   sudo mkdir /etc/alertmanager/

  cat <<EOF | sudo tee /etc/alertmanager/alertmanager.yml
global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 20s
  group_intervals: 1m
  repeat_interval: 2m 
  receiver: 'email'
receivers:
- name: 'email_configs'
  email_configs:
  - to: 'sman27055@gmail.com'
    from: 'sman27055@gmail.com'
    smarthost: 'smtp.google.com:587'
    auth_username: 'sman27055@gmail.com'
    auth_identity: 'sman27055@gmail.com'
    auth_password: '99851721'
EOF'


 sudo systemctl enable alertmanager
 sudo systemctl start alertmanager

  sudo systemctl enable grafana-server
  sudo systemctl start grafana-server
  sudo systemctl enable prometheus
  sudo systemctl start prometheus


  sudo bash -c 'cat <<EOF > /etc/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["vm1:9100"]

  - job_name: "mysqld_exporter"
    static_configs:
      - targets: ["vm1:9104"]
EOF'


  sudo bash -c 'cat <<EOF > /etc/prometheus/alert.rules.yml
groups:
- name: instance_high_cpu_usage
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[1m]))) > 10
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} has high CPU usage"
      description: "CPU usage is above 10% (current value is: {{ $value }}%)"
EOF'
SHELL
  end
end