version: '3'

services:
  mysql-server:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database

  python-app:
    build:
      context: .
      dockerfile: Docker2
    depends_on:
      - mysql-server

